image: ubuntu

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: example.com
  script:
    - ssh $USER@SERVER_IP "cd $PATH_OF_THE_APPLICATION && git checkout $BRANCH_NAME && git pull origin $BRANCH_NAME && exit"
  only:
    - $BRANCH_NAME


